"""empty message

Revision ID: 4425b9125e30
Revises: 602c138e49cc
Create Date: 2017-10-27 23:59:04.548366

"""

# revision identifiers, used by Alembic.
revision = '4425b9125e30'
down_revision = '602c138e49cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'name')
    # ### end Alembic commands ###
