"""empty message

Revision ID: 602c138e49cc
Revises: 48b852d102fd
Create Date: 2017-10-27 23:54:08.524629

"""

# revision identifiers, used by Alembic.
revision = '602c138e49cc'
down_revision = '48b852d102fd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
