"""empty message

Revision ID: 6c149639a60d
Revises: 4425b9125e30
Create Date: 2017-10-28 00:37:44.001766

"""

# revision identifiers, used by Alembic.
revision = '6c149639a60d'
down_revision = '4425b9125e30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
